MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 50000, 80000, 110000, 140000]
RPN:
  FOCAL_LOSS: False
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 64
  WIDTH_PER_GROUP: 4
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 35
  ROI_XFORM_SAMPLING_RATIO: 2
  MLP_HEAD_DIM: 1024
TRAIN:
  WEIGHTS: roi28_new.pkl
  DATASETS: ('traffic_train', 'traffic_val')
  SCALES: (500, 600, 700, 800)
  MAX_SIZE: 1333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  DATASET_CACHE_PATH: 'detectron/datasets/data/traffic/cache/'
TEST:
  DATASETS: ('traffic_val',)
  NMS: 0.3
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 300
   # -- Test time augmentation example -- #
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    COORD_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    H_FLIP: True
    SCALES: (500, 600, 700, 800)
    MAX_SIZE: 3000
    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    AREA_TH_LO: 50   # 50^2
    AREA_TH_HI: 250000  # 180^2
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.9
OUTPUT_DIR: .
