MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 47
  FASTER_RCNN: True
NUM_GPUS: 2
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
  MLP_HEAD_DIM: 1024
TRAIN:
  WEIGHTS: imagenet_models/R-50.pkl
  DATASETS: ('cloth_train',)
  SCALES: (600, 800, 1000)
  MAX_SIZE: 2333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 32
  RPN_BATCH_SIZE_PER_IM: 32
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  DATASET_CACHE_PATH: 'detectron/datasets/data/cloth/cache/'
TEST:
  DATASETS: ('coco_2014_minival',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000

   # -- Test time augmentation example -- #
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    COORD_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    H_FLIP: True
    SCALES: ( 1000, 1500)
    MAX_SIZE: 5000


    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    AREA_TH_LO: 50   # 50^2
    AREA_TH_HI: 250000  # 180^2
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.9
OUTPUT_DIR: .
