MODEL:
  TYPE: retinanet
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 47
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0001
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_RPN: True
  RPN_MAX_LEVEL: 5
  RPN_MIN_LEVEL: 3
  COARSEST_STRIDE: 128
  EXTRA_CONV_LEVELS: True
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 64
  WIDTH_PER_GROUP: 4
RETINANET:
  RETINANET_ON: True
  NUM_CONVS: 2
  ASPECT_RATIOS: (0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10.0)
  SCALES_PER_OCTAVE: 3
  ANCHOR_SCALE: 4
  LOSS_GAMMA: 2.0
  LOSS_ALPHA: 0.25
TRAIN:
  WEIGHTS:  ret-x-101-backbone.pkl
  DATASETS: ('cloth_train',)
  SCALES: (500,800)
  MAX_SIZE: 2333
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 32
  RPN_BATCH_SIZE_PER_IM: 32
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  DATASET_CACHE_PATH: 'detectron/datasets/data/cloth/cache/'
  RPN_STRADDLE_THRESH: -1  # default 0
TEST:
  DATASETS: ('cloth_train',)
  NMS: 0.3
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 100

  # -- Test time augmentation example -- #
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    COORD_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    H_FLIP: True
    SCALES: ( 320, 480, 600, 960, 1000, 1920, 2560)
    MAX_SIZE: 80000


    SCALE_H_FLIP: True
    SCALE_SIZE_DEP: False
    AREA_TH_LO: 50   # 50^2
    AREA_TH_HI: 25000000  # 180^2
    ASPECT_RATIOS: ()
    ASPECT_RATIO_H_FLIP: False
  BBOX_VOTE:
    ENABLED: True
    SCORING_METHOD: IOU_AVG
    VOTE_TH: 0.1
OUTPUT_DIR: .