MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
NUM_GPUS: 2
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  # 2x schedule (note TRAIN.IMS_PER_BATCH: 1)
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 120000
  STEPS: [0, 80000, 100000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ASPECT_RATIOS: (1.,)
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_transformation
  NUM_GROUPS: 64
  WIDTH_PER_GROUP: 4
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
TRAIN:
  # md5sum of weights pkl file: aa14062280226e48f569ef1c7212e7c7
  # WEIGHTS: trained_models/hanzi/one_word/train/hanzi_train/generalized_rcnn/model_iter99999.pkl
  WEIGHTS: imagenet_models/X-101-64x4d.pkl
  DATASETS: ('hanzi_train', )
  DATASET_CACHE_PATH: 'detectron/datasets/data/'
  SCALES: (100, 200, 300, 400, 500)
  MAX_SIZE: 2333
  IMS_PER_BATCH: 1
  RPN_BATCH_SIZE_PER_IM: 64
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('hanzi_train',)
  NMS: 0.2
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
  DETECTIONS_PER_IM: 150
  BBOX_AUG:
    ENABLED: True
    SCORE_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    COORD_HEUR: UNION  # AVG NOTE: cannot use AVG for e2e model
    H_FLIP: True
    SCALES: (100, 200, 300, 400)
    MAX_SIZE: 3000
    # SCALE_H_FLIP: True
    # ASPECT_RATIOS: (0.7, 0.8, 1., 1.2, 1.3, )
    # ASPECT_RATIO_H_FLIP: True
  BBOX_VOTE:
    ENABLED: True
    VOTE_TH: 0.7
OUTPUT_DIR: .
